export type CargoMercadoRawLinha = {
  codigoOrigem: string;
  nome: string;
};

/**
 * Catalogo de Cargo de Mercado (RH), transcrito de docs/Cargo de Mercado.xls
 * fornecido pelo usuario (2026-08-26). Embutido como constante -- mesmo padrao
 * de plano-contas-raw.ts / grade-salarial-ctcea-raw.ts -- nunca fs.readFileSync
 * em runtime (ENOENT em serverless/Vercel).
 *
 * Fonte original tinha 184 linhas; 4 foram descartadas por serem placeholders
 * de lixo (nome so com x repetido, codigos 122/151/117/137) -- decisao do
 * usuario (ADR-047/US-139). Total: 180 linhas.
 */
export const CARGO_MERCADO_RAW: CargoMercadoRawLinha[] = [
  { codigoOrigem: '162', nome: 'ADMINISTRADOR' },
  { codigoOrigem: '1', nome: 'ADMINISTRADOR DE BANCO DE DADOS' },
  { codigoOrigem: '2', nome: 'ADMINISTRADOR DE REDES' },
  { codigoOrigem: '3', nome: 'ADMINISTRADOR DE SISTEMAS OPERACIONAIS' },
  { codigoOrigem: '4', nome: 'ADMINISTRADOR EM SEGURANCA DA INFORMACAO' },
  { codigoOrigem: '160', nome: 'ADVOGADO' },
  { codigoOrigem: '5', nome: 'ADVOGADO EMPRESARIAL' },
  { codigoOrigem: '159', nome: 'ADVOGADO SENIOR' },
  { codigoOrigem: '6', nome: 'ANALISTA ADMINISTRATIVO' },
  { codigoOrigem: '7', nome: 'ANALISTA ADMINISTRATIVO FINANCEIRO' },
  { codigoOrigem: '8', nome: 'ANALISTA CONTABIL' },
  { codigoOrigem: '9', nome: 'ANALISTA DE ALMOXARIFADO' },
  { codigoOrigem: '156', nome: 'ANALISTA DE BANCO DE DADOS - DBA' },
  { codigoOrigem: '10', nome: 'ANALISTA DE BENEFICIOS' },
  { codigoOrigem: '11', nome: 'ANALISTA DE BIBLIOTECA' },
  { codigoOrigem: '12', nome: 'ANALISTA DE CADASTRO' },
  { codigoOrigem: '13', nome: 'ANALISTA DE COBRANCA' },
  { codigoOrigem: '189', nome: 'ANALISTA DE COMERCIO EXTERIOR' },
  { codigoOrigem: '14', nome: 'ANALISTA DE COMPLIANCE' },
  { codigoOrigem: '15', nome: 'ANALISTA DE COMPRAS' },
  { codigoOrigem: '16', nome: 'ANALISTA DE CONTRATOS' },
  { codigoOrigem: '17', nome: 'ANALISTA DE CONTROLE DE QUALIDADE' },
  { codigoOrigem: '184', nome: 'ANALISTA DE CONTROLE INTERNO' },
  { codigoOrigem: '18', nome: 'ANALISTA DE CUSTOS' },
  { codigoOrigem: '19', nome: 'ANALISTA DE DESENVOLVIMENTO DE SISTEMAS' },
  { codigoOrigem: '20', nome: 'ANALISTA DE DOCUMENTACAO' },
  { codigoOrigem: '21', nome: 'ANALISTA DE EXPORTACAO E IMPORTACAO' },
  { codigoOrigem: '22', nome: 'ANALISTA DE FATURAMENTO' },
  { codigoOrigem: '23', nome: 'ANALISTA DE LICITAÇÃO OLD' },
  { codigoOrigem: '24', nome: 'ANALISTA DE LICITACOES' },
  { codigoOrigem: '25', nome: 'ANALISTA DE LOGISTICA' },
  { codigoOrigem: '26', nome: 'ANALISTA DE PATRIMONIO EMPRESARIAL' },
  { codigoOrigem: '186', nome: 'ANALISTA DE PROJETOS' },
  { codigoOrigem: '27', nome: 'ANALISTA DE PROJETOS LOGISTICOS' },
  { codigoOrigem: '28', nome: 'ANALISTA DE RECURSOS HUMANOS' },
  { codigoOrigem: '29', nome: 'ANALISTA DE RELACOES PUBLICAS' },
  { codigoOrigem: '163', nome: 'ANALISTA DE REQUISITOS' },
  { codigoOrigem: '30', nome: 'ANALISTA DE RISCOS' },
  { codigoOrigem: '180', nome: 'ANALISTA DE SISTEMAS' },
  { codigoOrigem: '153', nome: 'ANALISTA DE SUPORTE' },
  { codigoOrigem: '178', nome: 'ANALISTA DE SUPORTE TECNICO' },
  { codigoOrigem: '31', nome: 'ANALISTA DE TESOURARIA' },
  { codigoOrigem: '32', nome: 'ANALISTA DE TREINAMENTO' },
  { codigoOrigem: '33', nome: 'ANALISTA EM SEGURANCA DA INFORMACAO' },
  { codigoOrigem: '34', nome: 'ANALISTA FINANCEIRO' },
  { codigoOrigem: '35', nome: 'ANALISTA PEDAGOGICO' },
  { codigoOrigem: '36', nome: 'ANALISTA REDES E DE COMUNICACAO DE DADOS' },
  { codigoOrigem: '37', nome: 'ARQUITETO DE EDIFICACOES' },
  { codigoOrigem: '38', nome: 'ASSESSOR DE DIRETORIA' },
  { codigoOrigem: '188', nome: 'ASSESSOR EXECUTIVO' },
  { codigoOrigem: '39', nome: 'ASSESSOR FINANCEIRO' },
  { codigoOrigem: '191', nome: 'ASSESSOR INSTITUCIONAL' },
  { codigoOrigem: '40', nome: 'ASSISTENTE ADMINISTRATIVO' },
  { codigoOrigem: '41', nome: 'ASSISTENTE ADMINISTRATIVO FINANCEIRO' },
  { codigoOrigem: '42', nome: 'ASSISTENTE DE ALMOXARIFADO' },
  { codigoOrigem: '44', nome: 'ASSISTENTE DE ARMAZENAMENTO' },
  { codigoOrigem: '45', nome: 'ASSISTENTE DE ASSISTENCIA TECN. DE INFORMATICA' },
  { codigoOrigem: '168', nome: 'ASSISTENTE DE ATENDIMENTO SENIOR' },
  { codigoOrigem: '46', nome: 'ASSISTENTE DE BIBLIOTECA' },
  { codigoOrigem: '47', nome: 'ASSISTENTE DE CADASTRO' },
  { codigoOrigem: '48', nome: 'ASSISTENTE DE COBRANCA' },
  { codigoOrigem: '49', nome: 'ASSISTENTE DE CUSTOS' },
  { codigoOrigem: '50', nome: 'ASSISTENTE DE EDIFICACOES' },
  { codigoOrigem: '51', nome: 'ASSISTENTE DE FATURAMENTO' },
  { codigoOrigem: '52', nome: 'ASSISTENTE DE LOGISTICA' },
  { codigoOrigem: '158', nome: 'ASSISTENTE DE LOGISTICA JUNIOR' },
  { codigoOrigem: '53', nome: 'ASSISTENTE DE MATERIAIS' },
  { codigoOrigem: '54', nome: 'ASSISTENTE DE ORCAMENTO' },
  { codigoOrigem: '55', nome: 'ASSISTENTE DE TELEFONIA' },
  { codigoOrigem: '200', nome: 'ASSISTENTE DE TI' },
  { codigoOrigem: '56', nome: 'ASSISTENTE ELETRICO' },
  { codigoOrigem: '57', nome: 'ASSISTENTE FINANCEIRO' },
  { codigoOrigem: '58', nome: 'ASSISTENTE SOCIAL' },
  { codigoOrigem: '190', nome: 'AUDITOR INTERNO' },
  { codigoOrigem: '59', nome: 'AUXILIAR DE LIMPEZA' },
  { codigoOrigem: '60', nome: 'CHEFE  CONTABIL' },
  { codigoOrigem: '61', nome: 'CHEFE ADMINISTRATIVO' },
  { codigoOrigem: '62', nome: 'CHEFE ALMOXARIFADO' },
  { codigoOrigem: '63', nome: 'CHEFE DE ATENDIMENTO' },
  { codigoOrigem: '64', nome: 'CHEFE DE BIBLIOTECA' },
  { codigoOrigem: '65', nome: 'CHEFE DE COBRANCA' },
  { codigoOrigem: '172', nome: 'CHEFE DE COMPRAS' },
  { codigoOrigem: '66', nome: 'CHEFE DE CONTABILIDADE' },
  { codigoOrigem: '67', nome: 'CHEFE DE CONTAS A PAGAR' },
  { codigoOrigem: '68', nome: 'CHEFE DE CONTRATOS' },
  { codigoOrigem: '69', nome: 'CHEFE DE CUSTOS' },
  { codigoOrigem: '70', nome: 'CHEFE DE DEPARTAMENTO PESSOAL' },
  { codigoOrigem: '71', nome: 'CHEFE DE LOGISTICA' },
  { codigoOrigem: '72', nome: 'CHEFE DE PLANEJAMENTO DE OBRAS' },
  { codigoOrigem: '73', nome: 'CHEFE DE PLANEJAMENTO ESTRATEGICO' },
  { codigoOrigem: '74', nome: 'CHEFE DE RECURSOS HUMANOS' },
  { codigoOrigem: '75', nome: 'CHEFE DE TECNOLOGIA DA INFORMACAO' },
  { codigoOrigem: '76', nome: 'CHEFE DE TELECOMUNICACOES' },
  { codigoOrigem: '165', nome: 'CHEFE DESENVOLVEDOR DE SISTEMAS' },
  { codigoOrigem: '77', nome: 'CHEFE FINANCEIRO' },
  { codigoOrigem: '78', nome: 'CHEFE SETOR TECNOLOGIA DA INFORMACAO' },
  { codigoOrigem: '79', nome: 'COMPRADOR' },
  { codigoOrigem: '164', nome: 'COMUNICAÇÃO SOCIAL' },
  { codigoOrigem: '80', nome: 'CONTADOR' },
  { codigoOrigem: '155', nome: 'COORD. DE OPERAÇÕES DE LOGÍSTICA' },
  { codigoOrigem: '81', nome: 'COORDENADOR DE LOGISTICA' },
  { codigoOrigem: '82', nome: 'COORDENADOR DE MEIO AMBIENTE' },
  { codigoOrigem: '83', nome: 'COORDENADOR DE OBRAS' },
  { codigoOrigem: '166', nome: 'COORDENADOR DE PLANEJAMENTO E CONTROLE' },
  { codigoOrigem: '84', nome: 'COORDENADOR DE PROJETOS' },
  { codigoOrigem: '85', nome: 'COORDENADOR DE QUALIDADE' },
  { codigoOrigem: '181', nome: 'COORDENADOR DE SISTEMAS' },
  { codigoOrigem: '86', nome: 'COORDENADOR DE SISTEMAS DA INFORMACAO' },
  { codigoOrigem: '87', nome: 'COORDENADOR DE TECNOLOGIA DA INFORMACAO' },
  { codigoOrigem: '88', nome: 'COORDENADOR JURIDICO' },
  { codigoOrigem: '89', nome: 'COPEIRO' },
  { codigoOrigem: '92', nome: 'DESENHISTA PROJETISTA' },
  { codigoOrigem: '90', nome: 'DESENHISTA PROJETISTA CONSTRUCAO CIVIL' },
  { codigoOrigem: '91', nome: 'DESENHISTA PROJETISTA ELETRONICO' },
  { codigoOrigem: '93', nome: 'DESENVOLVEDOR DE SISTEMA' },
  { codigoOrigem: '94', nome: 'DIRETOR ADMINISTRATIVO E FINANCEIRO' },
  { codigoOrigem: '95', nome: 'DIRETOR GERAL' },
  { codigoOrigem: '96', nome: 'DIRETOR PESQUISA E DESENVOLVIMENTO (P&D)' },
  { codigoOrigem: '167', nome: 'ECONOMISTA FINANCEIRO' },
  { codigoOrigem: '97', nome: 'ELETROTECNICO' },
  { codigoOrigem: '98', nome: 'ENCARREGADO DE PATRIMONIO' },
  { codigoOrigem: '99', nome: 'ENGENHEIRO AMBIENTAL' },
  { codigoOrigem: '100', nome: 'ENGENHEIRO CIVIL' },
  { codigoOrigem: '170', nome: 'ENGENHEIRO DE AUTOMAÇÃO' },
  { codigoOrigem: '101', nome: 'ENGENHEIRO DE PRODUCAO' },
  { codigoOrigem: '102', nome: 'ENGENHEIRO DE SISTEMAS DA COMPUTACAO' },
  { codigoOrigem: '103', nome: 'ENGENHEIRO DE TELECOMUNICACOES' },
  { codigoOrigem: '104', nome: 'ENGENHEIRO ELETRICISTA DE PROJETOS' },
  { codigoOrigem: '105', nome: 'ENGENHEIRO ELETRICO' },
  { codigoOrigem: '106', nome: 'ENGENHEIRO ELETRONICO' },
  { codigoOrigem: '107', nome: 'ENGENHEIRO MECANICO' },
  { codigoOrigem: '0', nome: 'ESTAGIÁRIO' },
  { codigoOrigem: '108', nome: 'GEOGRAFO' },
  { codigoOrigem: '109', nome: 'GERENTE ADMINISTRATIVO' },
  { codigoOrigem: '183', nome: 'GERENTE DE COMPRRAS' },
  { codigoOrigem: '110', nome: 'GERENTE DE ENGENHARIA' },
  { codigoOrigem: '111', nome: 'GERENTE DE LOGISTICA' },
  { codigoOrigem: '112', nome: 'GERENTE DE OPERACOES' },
  { codigoOrigem: '113', nome: 'GERENTE DE PESQUISA E DESENVOLVIMENTO' },
  { codigoOrigem: '114', nome: 'GERENTE DE PROJETOS' },
  { codigoOrigem: '115', nome: 'GERENTE DE RECURSOS HUMANOS' },
  { codigoOrigem: '116', nome: 'GERENTE FINANCEIRO' },
  { codigoOrigem: '118', nome: 'HELPDESK' },
  { codigoOrigem: '157', nome: 'JOVEM APRENDIZ' },
  { codigoOrigem: '119', nome: 'LIDER DE ENGENHARIA' },
  { codigoOrigem: '124', nome: 'MENSAGEIRO' },
  { codigoOrigem: '171', nome: 'METEOROLOGISTA' },
  { codigoOrigem: '120', nome: 'MONTADOR DE ESTRUTURAS METALICAS' },
  { codigoOrigem: '121', nome: 'MOTORISTA' },
  { codigoOrigem: '154', nome: 'MOTORISTA DE CAMINHAO' },
  { codigoOrigem: '123', nome: 'MOTORISTA DE FURGAO OU VEICULO SIMILAR' },
  { codigoOrigem: '185', nome: 'OFFICE BOY' },
  { codigoOrigem: '125', nome: 'PINTOR' },
  { codigoOrigem: '126', nome: 'PROGRAMADOR DE SISTEMAS' },
  { codigoOrigem: '127', nome: 'SECRETARIA DE DIRETORIA' },
  { codigoOrigem: '128', nome: 'SUPERVISOR DE BENEFICIOS' },
  { codigoOrigem: '129', nome: 'SUPERVISOR FINANCEIRO' },
  { codigoOrigem: '130', nome: 'SUPERVISOR TECNICO' },
  { codigoOrigem: '131', nome: 'TEC. MECANICO' },
  { codigoOrigem: '161', nome: 'TÉCNICO CONTÁBIL' },
  { codigoOrigem: '132', nome: 'TECNICO DE DOCUMENTACAO E INFORMACAO' },
  { codigoOrigem: '133', nome: 'TECNICO DE EDIFICACOES' },
  { codigoOrigem: '134', nome: 'TECNICO DE INFORMATICA' },
  { codigoOrigem: '135', nome: 'TECNICO DE LOGISTICA' },
  { codigoOrigem: '136', nome: 'TECNICO DE MANUTENCAO' },
  { codigoOrigem: '138', nome: 'TECNICO DE MANUTENCAO ELETRICA' },
  { codigoOrigem: '139', nome: 'TECNICO DE OBRAS' },
  { codigoOrigem: '140', nome: 'TECNICO DE OBRAS DE INFRAESTRUTURA' },
  { codigoOrigem: '142', nome: 'TECNICO DE PLANEJAMENTO DE PRODUCAO' },
  { codigoOrigem: '182', nome: 'TECNICO DE SUPORTE' },
  { codigoOrigem: '144', nome: 'TECNICO DE TELEFONIA' },
  { codigoOrigem: '145', nome: 'TECNICO ELETRICISTA' },
  { codigoOrigem: '146', nome: 'TECNICO ELETRONICO' },
  { codigoOrigem: '147', nome: 'TECNICO EM BIBLIOTECONOMIA' },
  { codigoOrigem: '148', nome: 'TECNICO EM ELETROMECANICA' },
  { codigoOrigem: '149', nome: 'TECNICO EM MECANICA DE PRECISAO' },
  { codigoOrigem: '150', nome: 'TECNICO EM SEGURANCA NO TRABALHO' },
  { codigoOrigem: '152', nome: 'TECNICO MECANICO' },
  { codigoOrigem: '141', nome: 'TECNICO ORÇAMENTISTA' },
  { codigoOrigem: '169', nome: 'TÉCNICO PROJETOS ELÉTRICO' },
];
